#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(NICTA_GPL)
#

ifdef SELF_TEST
C_SOURCES += src/selftest/crc32.c \
             src/selftest/checksum.c
endif

